apiVersion: v1
kind: Pod
metadata:
  name: busybox-emptydir
spec:
  containers:
  - name: busybox-emptydir
    image: busybox
    args:
    - sleep
    - 100000
    volumeMounts:
    - name: emptydir
      mountPath: /emptydir
  volumes:
  - name: emptydir
    emptyDir: {}
